Init repo
openprocurement/openprocurement.ansible.edr pull request #1
Opened 2017-03-20 15:41 UTC by Krokop

2017-03-21 10:56 UTC, kroman0 requested changes

2017-03-21 10:56 UTC, kroman0 commented on roles/server/tasks/main.yml
> +- name: Create virtualenv
Середовище потрібно розбудовувати з допомогою buildout. Можете подати PR з buildout на 
https://github.com/openprocurement/openprocurement.buildout

2017-03-21 10:56 UTC, kroman0 commented on roles/server/tasks/main.yml
> +  shell: setsebool -P httpd_can_network_connect 1
nginx мав би доступатись до дозволених йому портів, тому аплікацію доцільно запускати на 8008, 8009 чи 9000

2017-03-21 10:56 UTC, kroman0 commented on roles/server/templates/openprocurement.integrations.edr.ini.j2
> +[filter:server_cookie]
Потрібно винести в buildout і для проксі ServerCookieMiddleware не потрібен

2017-03-21 10:56 UTC, kroman0 commented on roles/server/tasks/main.yml
> +    - virtualenv
В buildout потрібно зафіксувати версії з якими працює проксі

2017-03-21 10:56 UTC, kroman0 commented on group_vars/all
> +deploy_user: root
Розбудовувати потрібно користувачем з обмеженими правами

2017-03-21 10:56 UTC, kroman0 commented on dev_playbook.yml
> +      nginx_user: "root"
nginx не можна запускати користувачем з повними правами

2017-03-21 11:53 UTC, Krokop commented on roles/server/tasks/main.yml
> +  shell: setsebool -P httpd_can_network_connect 1
Зробив 8008

2017-03-21 11:54 UTC, Krokop commented
@kroman0 На нашу думку ansible був потрібен, щоб прибрати buildout. Які переваги в buildout + ansible?

2017-03-21 11:59 UTC, Krokop commented on dev_playbook.yml
> +      nginx_user: "root"
Змінив на nginx_user, але потрібно не забути створити його на новому сервері.

2017-03-21 12:44 UTC, Krokop commented on roles/server/templates/openprocurement.integrations.edr.ini.j2
> +[filter:server_cookie]
З правок ТЗ https://docs.google.com/document/d/15DDWEL0MQGx6ZsZIHbxYJ8hHsDbn0APDUe_iv1q_34E/edit# - Фіксування ідентифікаторів запитів за допомогою механізмів X-Client-Request-ID, X-Request-ID

2017-03-21 12:47 UTC, kroman0 commented on dev_playbook.yml
> +      nginx_user: "root"
При встановленні nginx створюється користувач nginx і не треба нового користувача створювати. Можете забрати nginx_user

2017-03-21 13:20 UTC, kroman0 commented on roles/server/templates/openprocurement.integrations.edr.ini.j2
> +[filter:server_cookie]
Для цього є RequestIdMiddleware

2017-03-21 13:25 UTC, kroman0 commented
buildout для розбудови аплікації проксі, а ansible для розбудови всього середовища для проксі

2017-03-21 13:28 UTC, Krokop commented
Ок, на зустрічі ми обговорювали окреми buildout. Можливо репозиторій вже є?

2017-03-21 14:07 UTC, kroman0 commented
https://github.com/openprocurement/openprocurement.edr.buildout

2017-03-23 15:58 UTC, Krokop commented
@kroman0 потрібен ревью

2017-03-24 09:41 UTC, Krokop commented
@kroman0 потрібен ревью

2017-03-24 11:04 UTC, kroman0 requested changes

2017-03-24 11:04 UTC, kroman0 commented on roles/server/tasks/main.yml
> +    - python-pip
pip не потрібно встановлювати

2017-03-24 11:04 UTC, kroman0 commented on roles/server/tasks/main.yml
> +- name: Upgrade global pip
І цього не потрібно?

2017-03-24 11:16 UTC, Krokop commented on roles/server/tasks/main.yml
> +- name: Upgrade global pip
прибрав та провів тест

2017-03-24 11:16 UTC, Krokop commented on roles/server/tasks/main.yml
> +    - python-pip
прибрав

2017-03-24 12:30 UTC, Krokop commented
@kroman0 потрібен ревью

2017-03-24 13:24 UTC, ktarasz reviewed
- Додати створення користувача без sudo і розбудова користувацького середовища від даного користувача.
- Необхідно виділити роль, що стосується встановлення пакетів та роль для побудови користувацького середовища.
- Розібратись із пакетами які необхідні для побудови
- Виписати залежності

2017-03-24 13:24 UTC, ktarasz commented on roles/server/tasks/main.yml
> +    - yum
Навіщо yum?

2017-03-24 13:24 UTC, ktarasz commented on dev_playbook.yml
> +      role: geerlingguy.nginx
Залежність на зовнішню роль geerlingguy.nginx. Додайте як залежність і також опишіть із якою версією ansible працює playbook в README

2017-03-24 13:24 UTC, ktarasz commented on roles/server/tasks/main.yml
> +- name: Create dir for code
Create dir for code та Installs necessary packages for fedora виконуються від одного користувача?
Більше того task Installs package виконується без sudo чи become.
Тобто є передумова, що даний користувач саме  root (це не коректно).  Після чого buildout збирається та запускається тим же користувачем (root) це не коректно.
(Можна робити із https://galaxy.ansible.com/mivok0/users/ або https://galaxy.ansible.com/sansible/users_and_groups/)

2017-03-24 13:24 UTC, ktarasz commented on roles/server/tasks/main.yml
> +  register: copy_buildout_config
copy_buildout_config - навіщо реєструвати ?

2017-03-24 13:24 UTC, ktarasz commented on roles/server/tasks/main.yml
> +  template: src=buildout.cfg.j2 dest={{ path_to_code }}/buildout.cfg
Краще не {{ path_to_code }}/buildout.cfg , а {{ path_to_code }}/api.cfg

тоді 
- python bootstrap.py -с api.cfg
- bin/buildout -N -с api.cfg

2017-03-24 13:24 UTC, ktarasz commented on roles/server/tasks/main.yml
> +  shell: "python bootstrap.py chdir={{ path_to_code }}"
Зауваження не критичне:
python bootstrap.py - не потрібно робити кожного разу (Початкова розбудова і перебудова)

2017-03-24 13:24 UTC, ktarasz commented on roles/server/tasks/main.yml
> +  shell: "{{ path_to_code }}/bin/circusctl reload webapp"
Краще chdir={{ path_to_code }} із bin/circusctl reload webapp

2017-03-24 13:24 UTC, ktarasz commented on dev_playbook.yml
> +- hosts: server
remote_user ?

2017-03-24 13:24 UTC, ktarasz commented on roles/server/tasks/main.yml
> +  with_items:
Чи потрібно sqlite, redis, couchdb (https://github.com/openprocurement/openprocurement.integrations.edr/blob/master/setup.py#L5)

2017-03-24 13:38 UTC, Krokop commented on roles/server/tasks/main.yml
> +  with_items:
В версії 0.1 не потрібно

2017-03-24 14:26 UTC, Krokop commented on roles/server/tasks/main.yml
> +    - yum
потрібен для geerlingguy.nginx

2017-03-24 15:20 UTC, Krokop commented on dev_playbook.yml
> +      role: geerlingguy.nginx
Додав README

2017-03-24 15:22 UTC, Krokop commented
@ktarasz Додав створення нового користувача, і від його імені розгортаю buildout. Потрібен ревью.

2017-03-27 08:45 UTC, kroman0 commented on dev_playbook.yml
> +- hosts: server
remote_user ?

2017-03-27 09:20 UTC, Krokop commented on dev_playbook.yml
> +- hosts: server
@kroman0 не зрозумів

2017-03-27 11:17 UTC, Krokop commented on dev_playbook.yml
> +- hosts: server
@kroman0 додав remote_user

2017-03-27 16:08 UTC, ktarasz commented
Склонував репозиторій.
Зміни для роботи із сервером (deploy_user та servers група для hosts)
deploy_user: quintagroup.com (користувач із sudo)
server: 192.168.3.249 (fedora 25 cloud із quintagroup.com користувачем)

_$ id
uid=1000(quintagroup.com) gid=1000(quintagroup.com) groups=1000(quintagroup.com),4(adm),10(wheel),190(systemd-journal)_

```
$ git diff
diff --git a/group_vars/all b/group_vars/all
index 11d69e0..6313805 100644
--- a/group_vars/all
+++ b/group_vars/all
@@ -1,6 +1,6 @@
 
 # Remote user
-deploy_user: proxy_user
+deploy_user: quintagroup.com
 
 # User need for building proxy
 build_user: edr_integration
diff --git a/hosts b/hosts
index b48d129..39727e3 100644
--- a/hosts
+++ b/hosts
@@ -1 +1,2 @@
 [server]
+192.168.3.249
```

Результат:

```
$ ansible-playbook dev_playbook.yml -i hosts 
PLAY [server] ******************************************************************

TASK [setup] *******************************************************************
ok: [192.168.3.249]

TASK [users : Add group] *******************************************************
fatal: [192.168.3.249]: FAILED! => {"changed": false, "failed": true, "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "edr_group"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @dev_playbook.retry

PLAY RECAP *********************************************************************
192.168.3.249              : ok=1    changed=0    unreachable=0    failed=1   
```

2017-03-27 17:51 UTC, Krokop commented
@ktarasz додав become true для створення нового користувача та групи.

Для збору production версії потрібно, зібрати proxy в пакет `openprocurement.integrations.edr==0.1.0` та завантажити на http://op:x9W3jZ@dist.quintagroup.com/op/ .
Зараз можно побудувати тільки development.cfg, для цього відредагуйте api.cfg.j2.

2017-03-28 09:29 UTC, ktarasz commented
Як перевіряється
curl "localhost/api/1.0/verify?id=14360570" -u robot:robot
openprocurement/openprocurement.ansible.edr#1
?

2017-03-28 10:15 UTC, Krokop commented
Ящур локально то без /api/1.0.

2017-03-28 10:43 UTC, ktarasz commented
[edr_integration@192-168-3-249-untrusted edr_integrations]$ curl "127.0.0.1/api/1.0/verify?id=14360570" -u robot:robot -I
HTTP/1.1 403 Forbidden
Server: nginx/1.10.2
Date: Tue, 28 Mar 2017 10:42:51 GMT
Content-Type: application/json
Content-Length: 128
Connection: keep-alive
X-Request-ID: req-4235149c-0fc0-437c-a962-ecf3df9ea646

2017-03-28 10:44 UTC, Krokop commented
Якщо локально curl "localhost:8008/verify?id=14360570" -u robot:robot

2017-03-28 10:46 UTC, ktarasz commented
Oleg Serbokryl @Krokop 13:43
працює, відповідь від ЄДР АПІ
токен невалідний

Taras Kozlovskyi @ktarasz 13:45
А який токен в білдауті
?

2017-03-28 10:51 UTC, ktarasz commented
Доповніть інструкцію що потрібно мати токен з  https://zqedr-www.nais.gov.ua/en/ і місце в  ansible де потрібно його вставити

```
Taras Kozlovskyi @ktarasz 13:46
ок як перевірити що воно працює коректно?

Oleg Serbokryl @Krokop 13:46
Вам потрібно отримати токен в https://zqedr-www.nais.gov.ua/en/
```

2017-03-28 11:15 UTC, Krokop commented
@ktarasz додав https://github.com/openprocurement/openprocurement.ansible.edr/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R14

2017-03-28 11:29 UTC, ktarasz commented
[edr_integration@192-168-3-249-untrusted edr_integrations]$ curl "127.0.0.1/api/1.0/verify?id=14360570" -u robot:robot -i
HTTP/1.1 200 OK
Server: nginx/1.10.2
Date: Tue, 28 Mar 2017 11:28:54 GMT
Content-Type: application/json
Content-Length: 612
Connection: keep-alive
X-Request-ID: req-86e8652a-ef9a-4130-90b1-618c10287531

{"data": [{.................}]}

2017-03-28 11:29 UTC, ktarasz commented
І питання, як перевірити що сервер працює (лінк на який можна ходити кожні 30 сек і отримувати 200 OK)

2017-03-28 11:32 UTC, Krokop commented
@ktarasz зараз немає такого функціоналу, але можливо потрібно буде внести його в 2 реліз

2017-03-28 11:32 UTC, ktarasz commented
**Можна приймати pull request**

2017-03-28 11:33 UTC, ktarasz approved these changes

2017-03-28 11:33 UTC, kroman0 approved these changes

2017-03-28 11:34 UTC, merged

2017-03-28 11:35 UTC, ktarasz commented
https://github.com/openprocurement/openprocurement.integrations.edr/issues/20